name: Sync Shadowrocket Rules

on:
  schedule:
    # 每天UTC时间1点执行 (北京时间上午9点)
    - cron: '0 1 * * *'
  workflow_dispatch: # 允许在Actions页面手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync and update conf files
        run: |
          # 1. 定义要添加的各部分纯内容
          # Rule 内容
          cat > rule_content.txt << 'EOF'
          AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT
          AND,((DOMAIN,youtubei.googleapis.com), (PROTOCOL,UDP)),REJECT
          DOMAIN,ad.12306.cn,DIRECT
          DOMAIN-SUFFIX,iyes.youku.com,REJECT
          DOMAIN-SUFFIX,optimus-ads.amap.com,DIRECT
          EOF

          # URL Rewrite 内容
          cat > url_rewrite_content.txt << 'EOF'
          (^https?:\/\/[\w-]+\.googlevideo\.com\/(?!dclk_video_ads).+?)&ctier=L(&.+?),ctier,(.+) $1$2$3 302
          ^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?)).+&oad _ reject-200
          ^https?:\/\/(www|s)\.youtube\.com\/api\/stats\/ads _ reject-200
          ^https?:\/\/(www|s)\.youtube\.com\/(pagead|ptracking) _ reject-200
          ^https?:\/\/s\.youtube\.com\/api\/stats\/qoe\?adcontext _ reject-200
          ^https?:\/\/app\.bilibili\.com\/x\/v2\/splash\/show url reject-200
          # > 闲鱼
          ^https?:\/\/(g-)?acs\.m\.goofish\.com\/gw\/mtop.*splash\.ads - reject
          ^https?:\/\/(g-)?acs\.m\.goofish\.com\/gw\/mtop.idle.ad.expose - reject
          # > 高德地图
          ^https?:\/\/.*\.amap\.com\/ws\/faas\/amap-navigation\/card-service-route-plan\? url reject-dict
          ^https?:\/\/.*\.amap\.com\/ws\/boss\/order_web\/\w{8}_information url reject-200
          ^https?:\/\/.*\.amap\.com\/ws\/asa\/ads_attribution url reject
          ^https?:\/\/.*\.amap\.com\/ws\/shield\/scene\/recommend url reject-dict
          ^https?:\/\/.*\.amap\.com\/uploadimg\/\w+\.gif url reject-img
          ^https?:\/\/.*\.amap\.com\/ws\/valueadded\/weather url reject-dict
          EOF

          # Script 内容
          cat > script_content.txt << 'EOF'
          12306.js= type=http-request, pattern=^https?:\/\/ad\.12306\.cn\/ad\/ser\/getAdList, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/refs/heads/master/12306.js, requires-body=true, max-size=-1, timeout=60
          youtube.response = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch),requires-body=1,max-size=-1,binary-body-mode=1,engine=jsc,script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/youtube.response.js,argument="{"lyricLang":"off","captionLang":"off","blockUpload":true,"blockImmersive":true,"debug":false}"
          spotify-json = type=http-request,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,requires-body=0,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-json.js
          spotify-proto = type=http-response,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-proto.js,script-update-interval=0
          bilibili_json = type=http-response,pattern=^https?:\/\/app\.bilibili\.com\/x\/(v2\/splash\/list|v2\/account\/myinfo\?|v2\/feed\/index|resource\/show\/tab|v2\/account\/mine|resource\/top\/activity|v2\/search\/square),requires-body=1,max-size=-1,script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/refs/heads/master/bilibili_json.js
          # > AMDC处理 (已合并高德地图规则)
          amdc = type=http-response,pattern=(^http:\/\/[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+){1,4}(:\d+)?\/amdc\/mobileDispatch|^http:\/\/amdc\.m\.taobao\.com),requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/refs/heads/master/amdc.js
          # > 高德地图脚本合并
          amap_js = type=http-response,pattern=^https?:\/\/.*\.amap\.com\/(ws\/message\/notice\/list|ws\/shield\/frogserver\/aocs\/updatable|ws\/shield\/search\/nearbyrec_smart|ws\/promotion-web\/resource|ws\/faas\/amap-navigation\/main-page|ws\/valueadded\/alimama\/splash_screen|ws\/msgbox\/pull|ws\/shield\/dsp\/profile\/index\/nodefaas|ws\/shield\/search\/new_hotword),requires-body=1,script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/refs/heads/master/amap.js
          EOF
          
          # Header Rewrite 内容
          cat > header_rewrite_content.txt << 'EOF'
          http-request ^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/user-customization-service\/v1\/customize$ header-del if-none-match
          EOF
          
          # Body Rewrite 内容
          cat > body_rewrite_content.txt << 'EOF'
          # > 闲鱼
          http-response-jq ^https?:\/\/(g-)?acs\.m\.goofish\.com\/gw\/mtop.taobao.idle.user.strategy.list '.data.strategies = [{}]'
          http-response-jq ^https?:\/\/(g-)?acs\.m\.goofish\.com\/gw\/mtop.taobao.idlehome.home.circle.list '.data.circleList |= map(select(.bizCode != "saveMoney"))'
          http-response-jq ^https?:\/\/(g-)?acs\.m\.goofish\.com\/gw\/mtop.taobao.idlehome.home.nextfresh '.data.homeTopList |= [ .[0] ] | .data.sections |= map(select(.data.bizType == "item"))'
          http-response-jq ^https?:\/\/(g-)?acs\.m\.goofish\.com\/gw\/mtop.taobao.idlemtopsearch.search.shade '.data.singleShadeWords =[{}]'
          http-response-jq ^https?:\/\/(g-)?acs\.m\.goofish\.com\/gw\/mtop.taobao.idlemtopsearch.item.search.activate '.data.cardList = [{}]'
          http-response-jq ^https?:\/\/(g-)?acs\.m\.goofish\.com\/gw\/mtop.taobao.idlemtopsearch.search.discover 'del(.data.resultList)'
          http-response-jq ^https?:\/\/(g-)?acs\.m\.goofish\.com\/gw\/mtop.idle.user.page.my.adapter '.data.ability=[] | .data.container.sections |= map(select(.sectionBizCode | test("head|user|trade")))'
          http-response-jq ^https?:\/\/(g-)?acs\.m\.goofish\.com\/gw\/mtop.taobao.idle.item.buy.feeds 'del(.data.sections)'
          http-response-jq ^https?:\/\/(g-)?acs\.m\.goofish\.com\/gw\/mtop.taobao.idle.local.home '.data.sections |= map(select(.data.bizType == "item"))'
          http-response-jq ^https?:\/\/(g-)?acs\.m\.goofish\.com\/gw\/mtop.taobao.idlemtopsearch.search '.data.resultList |= map(select(.data.item.main.clickParam.args.biz_type == "item"))'
          http-response-jq ^https?:\/\/(g-)?acs\.m\.goofish\.com\/gw\/mtop.taobao.idle.item.recommend '.data.cardList |= map(select(.cardData.bizType != "mamaAD"))'
          http-response-jq ^https?:\/\/acs\.m\.taobao\.com\/gw\/mtop\.alibaba.*mytab '.data.model.children |= map(select(.name | contains("营销") | not))'
          EOF

          # 2. 定义一个通用的函数，用于将内容添加到已存在的区域，或创建新区域
          add_section() {
              local section_header="$1"
              local content_file="$2"
              local target_file="$3"
              local escaped_header=$(echo "$section_header" | sed 's/\[/\\[/g; s/\]/\\]/g')

              if grep -q "^${escaped_header}" "${target_file}"; then
                  sed -i "/^${escaped_header}/r ${content_file}" "${target_file}"
              else
                  echo "" >> "${target_file}"
                  echo "${section_header}" >> "${target_file}"
                  cat "${content_file}" >> "${target_file}"
              fi
          }

          # 3. 定义文件列表
          declare -A files=(
              ["sr_top500_banlist_ad.conf"]="https://johnshall.github.io/Shadowrocket-ADBlock-Rules-Forever/sr_top500_banlist_ad.conf"
              ["sr_cnip_ad.conf"]="https://johnshall.github.io/Shadowrocket-ADBlock-Rules-Forever/sr_cnip_ad.conf"
          )

          # 4. 循环处理每个文件
          for file in "${!files[@]}"; do
              url=${files[$file]}
              echo "Processing $file from $url"

              curl -sS -L -o "$file" "$url"

              echo "Sanitizing old MITM rules from $file..."
              sed -i '/^\[MITM\]/d' "$file"
              sed -i -E '/^[[:space:]]*hostname[[:space:]]*=/d' "$file"

              add_section "[Rule]" "rule_content.txt" "$file"
              add_section "[URL Rewrite]" "url_rewrite_content.txt" "$file"
              add_section "[Script]" "script_content.txt" "$file"
              add_section "[Header Rewrite]" "header_rewrite_content.txt" "$file"
              add_section "[Body Rewrite]" "body_rewrite_content.txt" "$file"

              echo "Rebuilding MITM section in $file..."
              echo "" >> "$file"
              echo "[MITM]" >> "$file"
              echo "hostname = *.google.cn, -redirector*.googlevideo.com, *.googlevideo.com, www.youtube.com, s.youtube.com, youtubei.googleapis.com, spclient.wg.spotify.com, *spclient.spotify.com, app.bilibili.com, m5.amap.com, m5-zb.amap.com, center.amap.com, acs-m.freshippo.com, acs.m.goofish.com, acs.m.taobao.com, ,guide-acs.m.taobao.com, acs4miniapp-inner.m.taobao.com, ad.12306.cn" >> "$file"
          done

          rm *.txt

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "feat(sync): Update rules for Amap, Goofish, Bilibili, etc."
            git push
          fi
